### ISSUE TITLE
Suggestions of writing some documentation

### ISSUE THREAD

**Issue by forhonourlx** [unixpickle/anyrl-py#32] opened 2018-08-23 13:03 UTC
Hi unixpickle,
anyrl-py is the most complete and terse reinforcement learning frameworks I've ever seen.
It is a great work!
Would you like write some documentation to make anyrl-py more popular?

Best wishes,
Simon

**Comment by unixpickle** [comment] 2018-08-23 19:20
Duplicate of #28.

Currently there are docstrings for almost every method and class, but what's missing is broader documentation about how to use everything together.

I would love if someone came in and

  1. created or pulled in a third-party a system for displaying documentation on a website,
  2. wrote high-level documentation for each of the modules.

**Closed by unixpickle** 2018-08-23 19:20 UTC
